import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#191F24',
    padding: 20,
  },
  saludo: {
    color: 'white',
    fontSize: 22,
    fontFamily: 'Montserrat',
    marginBottom: 4,
  },
  titulo: {
    color: '#3B99A3',
    fontSize: 20,
    fontFamily: 'Montserrat',
    marginBottom: 16,
    maxWidth: '60%',
  },
  barraBusqueda: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#121518',
    borderRadius: 10,
    paddingHorizontal: 10,
    marginBottom: 20,
  },
  iconoBusqueda: {
    marginRight: 8,
  },
  inputBusqueda: {
    flex: 1,
    color: 'white',
    fontFamily: 'Montserrat',
    paddingVertical: 10,
  },
  seccionTitulo: {
    color: 'white',
    fontSize: 16,
    fontFamily: 'Montserrat',
    marginVertical: 10,
  },
  serviciosContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  servicioBtn: {
    backgroundColor: '#121518',
    padding: 12,
    borderRadius: 12,
    width: '48%',
    marginVertical: 6,
    alignItems: 'center',
  },
  servicioTexto: {
    color: 'white',
    fontFamily: 'Montserrat',
    marginTop: 6,
    textAlign: 'center',
    fontSize: 13,
  },
  tecnicoCard: {
    backgroundColor: '#121518',
    borderRadius: 10,
    padding: 12,
    marginBottom: 12,
  },
  tecnicoInfo: {
    marginLeft: 8,
  },
  tecnicoDetalles: {
    color: '#ccc',
    fontSize: 13,
    fontFamily: 'Montserrat',
  },
  tecnicoInfoContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  tecnicoTextoContainer: {
    flex: 1,
    marginRight: 10,
    marginLeft: 10,
  },
  tecnicoNombre: {
    color: 'white',
    fontSize: 18,
    fontFamily: 'Montserrat',
    marginBottom: 4,
  },
  estrellasContainer: {
    flexDirection: 'row',
    marginBottom: 4,
  },
  ubicacionCalificacion: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  tecnicoPuntaje: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 24,
    marginLeft: 8,
    paddingRight: 18,
  },
  botonesContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
    marginBottom: 8,
  },
  botonAccion: {
    backgroundColor: '#191F24',
    paddingVertical: 10,
    borderRadius: 10,
    alignItems: 'center',
    flex: 1,
    marginHorizontal: 5,
  },
  botonTexto: {
    color: 'white',
    fontSize: 12,
    fontFamily: 'Montserrat',
    marginTop: 4,
  },
  tecnicoImagen: {
    width: 60,
    height: 60,
    borderRadius: 30,
    paddingRight: 20,
  },
  botonesFilaContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between', 
    marginTop: 12,
  },
  tecnicoBotones: {
    backgroundColor: '#191F24',
    borderRadius: 10,
    paddingHorizontal: 30,
    paddingVertical: 2,
  },
  flechaVolver: {
    marginBottom: 10,
  },
  botonAccion2: {
    backgroundColor: '#3B99A3',
    paddingVertical: 10,
    borderRadius: 10,
    alignItems: 'center',
    width: '100%',
    flex: 1,
    marginHorizontal: 5,
  },
});
